package eventpusher

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/Tata-Matata/fake-aria-api/util"
)

// generic event pusher
type EventPusher interface {
	Name() string
	Interval() time.Duration
	GenerateEvent() (any, error)
	Endpoint() string
}

// starts multiple event pushers based on the provided configurations
func StartEventPushers(pushers []EventPusher, exporterBaseURL string) {
	for _, pusher := range pushers {
		startEventPusher(pusher, exporterBaseURL)
	}
}

// starts a single event pusher to REST POST requests at regular intervals
func startEventPusher(pusher EventPusher, exporterBaseURL string) {

	//Starts an anonymous goroutine — a separate lightweight thread of execution.
	//Everything inside this anonymous function runs concurrently with the rest of the program.
	//pusher runs in the background and won’t block main() execution.
	go func(pusher EventPusher) {
		ticker := time.NewTicker(pusher.Interval())
		defer ticker.Stop()

		util.LogInfo(fmt.Sprintf("Started pusher %s", pusher.Name()))

		//loop waits for a message on the ticker’s channel C.
		//tick = every interval
		for range ticker.C {
			pushData(pusher, exporterBaseURL)
		}
		//calls the function immediately, passing pusher as the argument.
		//equivalent to definining func and calling it immediately
	}(pusher)
}

// pushes data generated by the pusher to the exporter endpoint
func pushData(pusher EventPusher, exporterBaseURL string) {

	//generate event data
	evt, err := pusher.GenerateEvent()
	if err != nil {
		util.LogInfo(fmt.Sprintf("%s failed to generate event: %v", pusher.Name(), err))
		return
	}

	//marshal event to json
	payload, err := json.Marshal(evt)
	if err != nil {
		util.LogInfo(fmt.Sprintf("JSON marshal error when creating event payload for pusher: %s Error details: %v", pusher.Name(), err))
		return
	}

	//push event to exporter endpoint
	url := exporterBaseURL + pusher.Endpoint()
	resp, err := http.Post(url, "application/json", bytes.NewBuffer(payload))
	if err != nil {
		util.LogInfo(fmt.Sprintf("%s failed to POST event to %s. Error details: %v", pusher.Name(), url, err))
		return
	}
	resp.Body.Close()

	util.LogInfo(fmt.Sprintf("[%s] Pushed event: %s\n", pusher.Name(), string(payload)))

}
